/* Generated By:JJTree: Do not edit this line. ASTArgumentImport.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgumentImport extends SimpleNode {
  public ASTArgumentImport(int id) {
    super(id);
  }

  public ASTArgumentImport(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b63ce69ab6422be73fa7f426080b3734 (do not edit this line) */
