/* Generated By:JJTree: Do not edit this line. ASTArgumentCall.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgumentCall extends SimpleNode {
  public ASTArgumentCall(int id) {
    super(id);
  }

  public ASTArgumentCall(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=403b09da6554b1fc54ec227c052bc8f2 (do not edit this line) */
