/* Generated By:JJTree: Do not edit this line. ASTArgument.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTArgument extends SimpleNode {
  public ASTArgument(int id) {
    super(id);
  }

  public ASTArgument(Parser p, int id) {
    super(p, id);
  }

  public void createSymbolTable(SymbolTable symbolTable) {
    String type;
    type = ((ASTType) children[0]).getType();
    Symbol symbol = new Symbol(type, ((ASTIdentifier) children[1]).getName());
    symbolTable.addSymbol(symbol);
  }
}
/*
 * JavaCC - OriginalChecksum=ca0c1b92b03522a6bbc53f5142e79b82 (do not edit this
 * line)
 */
