/* Generated By:JJTree: Do not edit this line. ASTArgumentCall.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgumentCall extends SimpleNode {
  public ASTArgumentCall(int id) {
    super(id);
  }

  public ASTArgumentCall(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c7cc40f3ac07c8607b039e45fbe2b294 (do not edit this line) */
