/* Generated By:JJTree: Do not edit this line. ASTAddSub.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAddSub extends SimpleNode {
  public ASTAddSub(int id) {
    super(id);
  }

  public ASTAddSub(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea57c935fea2f4c98db97d30641ddaa7 (do not edit this line) */
