/* Generated By:JJTree: Do not edit this line. ASTAddSub.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAddSub extends SimpleNode {
  public ASTAddSub(int id) {
    super(id);
  }

  public ASTAddSub(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=46b9fd2b14a0c08cb1f36814ae2248a9 (do not edit this line) */
