/* Generated By:JJTree: Do not edit this line. ASTBool.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBool extends SimpleNode {
  public ASTBool(int id) {
    super(id);
  }

  public ASTBool(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=798ca1c4815bd655c5dbcf9227aed76a (do not edit this line) */
