/* Generated By:JJTree: Do not edit this line. ASTBool.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBool extends SimpleNode implements ASTType {
  public ASTBool(int id) {
    super(id);
  }

  public ASTBool(Parser p, int id) {
    super(p, id);
  }

  public String getType(){
    return "Bool";
  }

}
/* JavaCC - OriginalChecksum=514f11913bfc2c81ec7cdd6e8df33155 (do not edit this line) */
