/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration extends SimpleNode {
  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(Parser p, int id) {
    super(p, id);
  }

  public void analyzeSemantics(SymbolTable table) {
    for (int i = 0; i< children.length; i++) {
      if (children[i] instanceof ASTMethod || children[i] instanceof ASTMainMethod) {
        ((SimpleNode) children[i]).analyzeSemantics(table);
      }
    }
  }

}
/* JavaCC - OriginalChecksum=a262ba2abf85183e715db1909b2e6512 (do not edit this line) */
