/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration extends SimpleNode {
  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(Parser p, int id) {
    super(p, id);
  }


  public void createSymbolTable(SymbolTable symbolTable) {
    if (children == null){
      return;
    }
    if(children[0] instanceof ASTExtends){
      Parser.getInstance().className = ((ASTIdentifier)((ASTExtends)children[0]).children[0]).getName();
      Parser.getInstance().extend = ((ASTIdentifier)((ASTExtends)children[0]).children[1]).getName();
      Parser.getInstance().addType(((ASTIdentifier)((ASTExtends)children[0]).children[0]).getName());
    }else {
      Parser.getInstance().className = ((ASTIdentifier)children[0]).getName();
      Parser.getInstance().addType(((ASTIdentifier)children[0]).getName());
    }

    for (int i = 0; i < children.length; i++) {
      ((SimpleNode) children[i]).createSymbolTable(symbolTable);
    }
  }


  public void analyzeSemantics(SymbolTable table) {
    for (int i = 0; i< children.length; i++) {
      if (children[i] instanceof ASTMethod || children[i] instanceof ASTMainMethod) {
        ((SimpleNode) children[i]).analyzeSemantics(table);
      }
    }
  }

}
/* JavaCC - OriginalChecksum=a262ba2abf85183e715db1909b2e6512 (do not edit this line) */
