/* Generated By:JJTree: Do not edit this line. ASTCOMMA.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCOMMA extends SimpleNode {
  public ASTCOMMA(int id) {
    super(id);
  }

  public ASTCOMMA(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=65cb466d5e6ca5af482fcb3c260cbed7 (do not edit this line) */
