/* Generated By:JJTree: Do not edit this line. ASTExtends.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExtends extends SimpleNode {
  public ASTExtends(int id) {
    super(id);
  }

  public ASTExtends(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d2b8ca966671a086eeb04021d7d2c072 (do not edit this line) */
