/* Generated By:JJTree: Do not edit this line. ASTEqualsExpression.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEqualsExpression extends SimpleNode {
  public ASTEqualsExpression(int id) {
    super(id);
  }

  public ASTEqualsExpression(Parser p, int id) {
    super(p, id);
  }

}

/* JavaCC - OriginalChecksum=e3b8de2614b53468a917f1bc0a1d662b (do not edit this line) */
