/* Generated By:JJTree: Do not edit this line. ASTFALSE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFALSE extends SimpleNode {
  public ASTFALSE(int id) {
    super(id);
  }

  public ASTFALSE(Parser p, int id) {
    super(p, id);
  }

  public String analyzeType(SymbolTable table) {
    return "Bool";
  }

  public boolean isInitialized(SymbolTable table) {
    return true;
  }

}
/* JavaCC - OriginalChecksum=3a1a8083b53cb9341688a2cd8e80d9d5 (do not edit this line) */
