/* Generated By:JJTree: Do not edit this line. ASTFALSE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFALSE extends SimpleNode {
  public ASTFALSE(int id) {
    super(id);
  }

  public ASTFALSE(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ac75785060fca7a0ca8b78f2fb7bd80e (do not edit this line) */
