/* Generated By:JJTree: Do not edit this line. ASTfunction.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunction extends SimpleNode {
  public ASTfunction(int id) {
    super(id);
  }

  public ASTfunction(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e32282036d533f98d2bbaf06ba78b738 (do not edit this line) */
