/* Generated By:JJTree: Do not edit this line. ASTIntArray.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIntArray extends SimpleNode implements ASTType{
  public ASTIntArray(int id) {
    super(id);
  }

  public ASTIntArray(Parser p, int id) {
    super(p, id);
  }

  public String getType(){
    return "Int[]";
  }
}
/* JavaCC - OriginalChecksum=b85538713c87a1c3191d52072cfc78dd (do not edit this line) */
