/* Generated By:JJTree: Do not edit this line. ASTInt.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInt extends SimpleNode {
  public ASTInt(int id) {
    super(id);
  }

  public ASTInt(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ff8f66d180dbd7c2e5da2e566fcfe6b (do not edit this line) */
