/* Generated By:JJTree: Do not edit this line. ASTInt.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInt extends SimpleNode implements ASTType{
  public ASTInt(int id) {
    super(id);
  }

  public ASTInt(Parser p, int id) {
    super(p, id);
  }

  public String getType(){
    return "Int";
  }

}
/* JavaCC - OriginalChecksum=6e2281bfd80124ca731e25e96103262b (do not edit this line) */
