/* Generated By:JJTree: Do not edit this line. ASTIntLiteral.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIntLiteral extends SimpleNode {
  public ASTIntLiteral(int id) {
    super(id);
  }

  public ASTIntLiteral(Parser p, int id) {
    super(p, id);
  }

  public String analyzeType(SymbolTable table) {
    return "Int";
  }

}
/* JavaCC - OriginalChecksum=3cbf5a57c95087c442314130215558ea (do not edit this line) */
