/* Generated By:JJTree: Do not edit this line. ASTIntArray.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIntArray extends SimpleNode {
  public ASTIntArray(int id) {
    super(id);
  }

  public ASTIntArray(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9b26754da9354961fdbc7d74b35c772c (do not edit this line) */
