/* Generated By:JJTree: Do not edit this line. ASTLSQUARE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLSQUARE extends SimpleNode {
  public ASTLSQUARE(int id) {
    super(id);
  }

  public ASTLSQUARE(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=26f2b32c749b29fe4e2c7f6f8a65d241 (do not edit this line) */
