/* Generated By:JJTree: Do not edit this line. ASTLENGTH.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLENGTH extends SimpleNode {
  public ASTLENGTH(int id) {
    super(id);
  }

  public ASTLENGTH(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2a71d37a8b048056bb09fedbe30398f3 (do not edit this line) */
