/* Generated By:JJTree: Do not edit this line. ASTMainMethod.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainMethod extends SimpleNode {
  public ASTMainMethod(int id) {
    super(id);
  }

  public ASTMainMethod(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eacb451820a536338a9d435227155bc6 (do not edit this line) */
