/* Generated By:JJTree: Do not edit this line. ASTMulDiv.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMulDiv extends SimpleNode {
  public ASTMulDiv(int id) {
    super(id);
  }

  public ASTMulDiv(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c029eb6960985b765c4a1e603e37ffbe (do not edit this line) */
