/* Generated By:JJTree: Do not edit this line. ASTMainMethod.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMainMethod extends SimpleNode {
  public ASTMainMethod(int id) {
    super(id);
  }

  public ASTMainMethod(Parser p, int id) {
    super(p, id);
  }

  public void createSymbolTable(SymbolTable symbolTable) {
    SymbolTable newTable = new SymbolTable(symbolTable);
    newTable.setStatic(true);
    Parser.getInstance().addMethod("main", newTable);

    if (children == null) return;
    this.table = newTable;

    for (int i = 0; i < children.length; i++) {
      ((SimpleNode) children[i]).createSymbolTable(newTable);
    }
  }

  public void analyzeSemantics(SymbolTable table) {
    for (int i = 0; i < children.length; i++) {
      if (children[i] instanceof ASTStatementDeclarations)
        ((SimpleNode) children[i]).analyzeSemantics(this.table);
    }
  }
}
/*
 * JavaCC - OriginalChecksum=f7d371b0ef1c99e47049a0dc2c3bb9bd (do not edit this
 * line)
 */
