/* Generated By:JJTree: Do not edit this line. ASTNewId.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNewId extends SimpleNode {
  public ASTNewId(int id) {
    super(id);
  }

  public ASTNewId(Parser p, int id) {
    super(p, id);
  }

  public String analyzeType(SymbolTable table) {
    return ((ASTIdentifier) children[0]).getType();
  }

  public boolean isInitialized(SymbolTable table) {
    return true;
  }

}
/* JavaCC - OriginalChecksum=1c5ecce8b399f06df2cfddd4cdce53c6 (do not edit this line) */
