/* Generated By:JJTree: Do not edit this line. ASTNewInt.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNewInt extends SimpleNode {
  public ASTNewInt(int id) {
    super(id);
  }

  public ASTNewInt(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a664216433fbe51f949bb3f802552f01 (do not edit this line) */
