/* Generated By:JJTree: Do not edit this line. ASTNEW.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEW extends SimpleNode {
  public ASTNEW(int id) {
    super(id);
  }

  public ASTNEW(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a0fe874174dc351abb16b01ef943ed2 (do not edit this line) */
