/* Generated By:JJTree: Do not edit this line. ASTNewInt.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.io.*;

public class ASTNewInt extends SimpleNode {
  public ASTNewInt(int id) {
    super(id);
  }

  public ASTNewInt(Parser p, int id) {
    super(p, id);
  }

  public String analyzeType(SymbolTable table) {
    String type = ((SimpleNode) children[0]).analyzeType(table);
    if (type.equals("Int")) {
      return "Int[]";
    }
    return "";
  }

  public boolean isInitialized(SymbolTable table) {
    return true;
  }

  public int generateCode(SymbolTable symbolTable, PrintWriter print){
    ((SimpleNode)children[0]).generateCode(symbolTable, print);
    print.println("\tnewarray int ");
    return 0;
  }

}
/* JavaCC - OriginalChecksum=78a29a3d2efaf93db3aedbe8ab8a6fba (do not edit this line) */
