/* Generated By:JJTree: Do not edit this line. ASTNEW.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEW extends SimpleNode {
  public ASTNEW(int id) {
    super(id);
  }

  public ASTNEW(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d71104f77e4f35d19bb312fd64bbeec5 (do not edit this line) */
