/* Generated By:JJTree: Do not edit this line. ASTPar.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPar extends SimpleNode {
  public ASTPar(int id) {
    super(id);
  }

  public ASTPar(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=19b60334fc1e2090e34ed5eaf57fc3de (do not edit this line) */
