/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTProgram extends SimpleNode {
  public ASTProgram(int id) {
    super(id);
  }

  public ASTProgram(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=94c2c5e1c9ec2939f839804a5dc310ba (do not edit this line) */
