/* Generated By:JJTree: Do not edit this line. ASTprintErrorMessage.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprintErrorMessage extends SimpleNode {
  public ASTprintErrorMessage(int id) {
    super(id);
  }

  public ASTprintErrorMessage(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9808823f2c3edc0734a9c8017cbda21b (do not edit this line) */
