/* Generated By:JJTree: Do not edit this line. ASTprintErrorMessage.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprintErrorMessage extends SimpleNode {
  public ASTprintErrorMessage(int id) {
    super(id);
  }

  public ASTprintErrorMessage(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=56cb5a8e6fb54b3986ead2841cd10104 (do not edit this line) */
