/* Generated By:JJTree: Do not edit this line. ASTParamList.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParamList extends SimpleNode {
  public ASTParamList(int id) {
    super(id);
  }

  public ASTParamList(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d86d4b3287f529b31bac5273502d0001 (do not edit this line) */
