/* Generated By:JJTree: Do not edit this line. ASTRSQUARE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRSQUARE extends SimpleNode {
  public ASTRSQUARE(int id) {
    super(id);
  }

  public ASTRSQUARE(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ff8afb0b19daac0b2c7495bb0c51d28c (do not edit this line) */
