/* Generated By:JJTree: Do not edit this line. ASTskipto.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTskipto extends SimpleNode {
  public ASTskipto(int id) {
    super(id);
  }

  public ASTskipto(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c0c1df87bcce5cc2bfb19e2e6654b993 (do not edit this line) */
