/* Generated By:JJTree: Do not edit this line. ASTskipto_dont_consume.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTskipto_dont_consume extends SimpleNode {
  public ASTskipto_dont_consume(int id) {
    super(id);
  }

  public ASTskipto_dont_consume(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a2b30619767b1434463e72ed1749a406 (do not edit this line) */
