/* Generated By:JJTree: Do not edit this line. ASTskip_all.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTskip_all extends SimpleNode {
  public ASTskip_all(int id) {
    super(id);
  }

  public ASTskip_all(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bbe77efd429101e408306516049a3ea3 (do not edit this line) */
