/* Generated By:JJTree: Do not edit this line. ASTskipto_while_expression.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTskipto_while_expression extends SimpleNode {
  public ASTskipto_while_expression(int id) {
    super(id);
  }

  public ASTskipto_while_expression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea3336607fdfff0ad6cea9c769df60cc (do not edit this line) */
