/* Generated By:JJTree: Do not edit this line. ASTStatementDeclarations.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementDeclarations extends SimpleNode {
  public ASTStatementDeclarations(int id) {
    super(id);
  }

  public ASTStatementDeclarations(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e7c4222be49b0f6513f9218f41ad850b (do not edit this line) */
