/* Generated By:JJTree: Do not edit this line. ASTStatic.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatic extends SimpleNode {
  public ASTStatic(int id) {
    super(id);
  }

  public ASTStatic(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0a8dc0e42602618c9fbdf43e11dfcc5 (do not edit this line) */
