/* Generated By:JJTree: Do not edit this line. ASTskipto_dont_consume.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTskipto_dont_consume extends SimpleNode {
  public ASTskipto_dont_consume(int id) {
    super(id);
  }

  public ASTskipto_dont_consume(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b226cb7968d9adad26402a1b3154a5c (do not edit this line) */
