/* Generated By:JJTree: Do not edit this line. ASTThen.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTThen extends SimpleNode {
  public ASTThen(int id) {
    super(id);
  }

  public ASTThen(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=630323c7bf8ddc7043b85c59f1bf710d (do not edit this line) */
