/* Generated By:JJTree: Do not edit this line. ASTTHIS.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTHIS extends SimpleNode {
  public ASTTHIS(int id) {
    super(id);
  }

  public ASTTHIS(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f2ea0067ef4bdc81eec429872826caad (do not edit this line) */
