import java.io.PrintWriter;

/* Generated By:JJTree: Do not edit this line. ASTTHIS.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTHIS extends SimpleNode {
  public ASTTHIS(int id) {
    super(id);
  }

  public ASTTHIS(Parser p, int id) {
    super(p, id);
  }

  public String analyzeType(SymbolTable table){
    return "this";
  }

  public int generateCode(SymbolTable table, PrintWriter print){
    print.println("\taload_0");
    return 1;
  }

}
/* JavaCC - OriginalChecksum=cc9ff3a6217769746e01f0b278090457 (do not edit this line) */
