/* Generated By:JJTree: Do not edit this line. ASTTRUE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.io.*;

public
class ASTTRUE extends SimpleNode {
  public ASTTRUE(int id) {
    super(id);
  }

  public ASTTRUE(Parser p, int id) {
    super(p, id);
  }

  public String analyzeType(SymbolTable table) {
    return "Bool";
  }

  public boolean isInitialized(SymbolTable table) {
    return true;
  }
  public int generateCode(SymbolTable symbolTable, PrintWriter print){
    print.println("\ticonst_1");
    return 1;
  }
}
/* JavaCC - OriginalChecksum=5faca07cfea9b92be7a30578746dc962 (do not edit this line) */
