/* Generated By:JJTree: Do not edit this line. ASTThen.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.io.*;

public
class ASTThen extends SimpleNode {
  public ASTThen(int id) {
    super(id);
  }

  public ASTThen(Parser p, int id) {
    super(p, id);
  }

  public int generateCode(SymbolTable symbolTable, PrintWriter print){
    if (children == null) return 0;

    int stackSize = 0;
    for (int i = 0; i < children.length; i++) {
      int newStackSize = ((SimpleNode) children[i]).generateCode(symbolTable, print);
      String retType = ((SimpleNode) children[i]).getReturnType();
      if (retType != null && !retType.equals("void")) {
          stackSize++;
          print.println("\tpop");
      }
      stackSize = Math.max(newStackSize, stackSize);
    }

    return stackSize;
  }

}
/* JavaCC - OriginalChecksum=630323c7bf8ddc7043b85c59f1bf710d (do not edit this line) */
