/* Generated By:JJTree: Do not edit this line. ASTVoid.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVoid extends SimpleNode implements ASTType{
  public ASTVoid(int id) {
    super(id);
  }

  public ASTVoid(Parser p, int id) {
    super(p, id);
  }

  public String getType(){
    return "void";
  }

}
/* JavaCC - OriginalChecksum=18b1bbaa25a6a65490d31ed502088a27 (do not edit this line) */
