/* Generated By:JJTree: Do not edit this line. ASTVariable.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariable extends SimpleNode {
  public ASTVariable(int id) {
    super(id);
  }

  public ASTVariable(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c962069d915fcf4e00666bf9b33ab39c (do not edit this line) */
