/* Generated By:JJTree: Do not edit this line. ASTVoid.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVoid extends SimpleNode {
  public ASTVoid(int id) {
    super(id);
  }

  public ASTVoid(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d678fa29d45ddd0dba1e45b2b5d2d7cb (do not edit this line) */
