/* Generated By:JJTree: Do not edit this line. ASTwhileError.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTwhileError extends SimpleNode {
  public ASTwhileError(int id) {
    super(id);
  }

  public ASTwhileError(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6d9f69e3a47af5ec600d9fb5a0de64c5 (do not edit this line) */
