/* Generated By:JJTree: Do not edit this line. ASTWhileExpression.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileExpression extends SimpleNode {
  public ASTWhileExpression(int id) {
    super(id);
  }

  public ASTWhileExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d40121962948aeb06f6297735bd4a527 (do not edit this line) */
