/* Generated By:JJTree: Do not edit this line. ASTWhileBody.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.io.*;

public
class ASTWhileBody extends SimpleNode {
  public ASTWhileBody(int id) {
    super(id);
  }

  public ASTWhileBody(Parser p, int id) {
    super(p, id);
  }

  public int generateCode(SymbolTable symbolTable, PrintWriter print){
    if (children == null) return 0;

    int stackSize = 0;
    for (int i = 0; i < children.length; i++) {
      stackSize = Math.max(((SimpleNode) children[i]).generateCode(symbolTable, print), stackSize);
    }
    return stackSize;
  }
}
/* JavaCC - OriginalChecksum=23f7c773ab5d9d496c29d3acdc634ae2 (do not edit this line) */
