/* Generated By:JJTree: Do not edit this line. ASTWhile.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.io.*;

public
class ASTWhile extends SimpleNode {
  public ASTWhile(int id) {
    super(id);
  }

  public ASTWhile(Parser p, int id) {
    super(p, id);
  }

  public int generateCode(SymbolTable symbolTable, PrintWriter print){
    SimpleNode expression = ((SimpleNode) children[0]);
    SimpleNode then = ((SimpleNode) children[1]); 
    int label = Parser.getAndIncLabel();
    String label_while = "else" + label; 
    String label_end = "endif" + label; 


    print.println(label_while + ":");
    int expStack = expression.generateCode(symbolTable, print);
    print.println(";while expr stack size: " + expStack);
    print.println("\tifeq " + label_end);
    int thenStack = then.generateCode(symbolTable, print);
    print.println("goto " + label_while);
    print.println(label_end+ ":");
    return Math.max(expStack, thenStack);
  }
}
/* JavaCC - OriginalChecksum=ea5543cc9a98027224f290be767d6430 (do not edit this line) */
