/* Generated By:JJTree: Do not edit this line. ASTWhileBody.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileBody extends SimpleNode {
  public ASTWhileBody(int id) {
    super(id);
  }

  public ASTWhileBody(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=23f7c773ab5d9d496c29d3acdc634ae2 (do not edit this line) */
